Advantage/ExternalApplications/AdvantageDataFixer/AdvantageDataFixer/Controllers/LeadsController.cs
using AdvantageDataFixer.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AdvantageDataFixer.Controllers
{
    using System.Web.Security;

    [Authorize]
    public class LeadsController : AuthorizedController
    {
        private AdvantageDb db;

        // GET: adLeads
        public ActionResult Index()
        {
            this.db = this.getAdvantageDb();

            if (this.db == null)
            {
                return Redirect(FormsAuthentication.LoginUrl);
            }

            var adLeads = db.adLeads.Include(a => a.adAdminCriteria).Include(a => a.adAgencySponsor).Include(a => a.adCitizenship).Include(a => a.adCounty).Include(a => a.adCountry).Include(a => a.adDegCertSeeking).Include(a => a.adDependencyType).Include(a => a.adEdLvl).Include(a => a.adEthCode).Include(a => a.adGender).Include(a => a.adGeographicType).Include(a => a.adLeadGroup).Include(a => a.adMaritalStatu).Include(a => a.adNationality).Include(a => a.adSourceAdvertisement).Include(a => a.adSourceCatagory).Include(a => a.adSourceType).Include(a => a.adVendorCampaign).Include(a => a.arAttendType).Include(a => a.arHousing).Include(a => a.arPrgGrp).Include(a => a.arPrgVersion).Include(a => a.arProgram).Include(a => a.arProgSchedule).Include(a => a.arShift).Include(a => a.plAddressType).Include(a => a.syCampus).Include(a => a.syFamilyIncome).Include(a => a.syInstitution).Include(a => a.syPrefix).Include(a => a.syState).Include(a => a.syState1).Include(a => a.syState2).Include(a => a.syStatusCode).Include(a => a.syStatus).Include(a => a.syStatus1).Include(a => a.syStatus2).Include(a => a.sySuffix).Include(a => a.syUser).Include(a => a.syUser1).Where(l => l.StudentId != Guid.Empty);
            return View(adLeads.ToList());
        }

        // GET: adLeads/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            this.db = this.getAdvantageDb();
            if (this.db == null)
            {
                return Redirect(FormsAuthentication.LoginUrl);
            }

            adLead adLead = db.adLeads.Find(id);
            if (adLead == null)
            {
                return HttpNotFound();
            }
            return View(adLead);
        }

        // GET: adLeads/Create
        public ActionResult Create()
        {
            this.db = this.getAdvantageDb();
            if (this.db == null)
            {
                return Redirect(FormsAuthentication.LoginUrl);
            }

            ViewBag.admincriteriaid = new SelectList(db.adAdminCriterias, "admincriteriaid", "Code");
            ViewBag.Sponsor = new SelectList(db.adAgencySponsors, "AgencySpId", "AgencySpCode");
            ViewBag.Citizen = new SelectList(db.adCitizenships, "CitizenshipId", "CitizenshipCode");
            ViewBag.County = new SelectList(db.adCounties, "CountyId", "CountyCode");
            ViewBag.Country = new SelectList(db.adCountries, "CountryId", "CountryCode");
            ViewBag.DegCertSeekingId = new SelectList(db.adDegCertSeekings, "DegCertSeekingId", "Code");
            ViewBag.DependencyTypeId = new SelectList(db.adDependencyTypes, "DependencyTypeId", "Code");
            ViewBag.PreviousEducation = new SelectList(db.adEdLvls, "EdLvlId", "EdLvlCode");
            ViewBag.Race = new SelectList(db.adEthCodes, "EthCodeId", "EthCode");
            ViewBag.Gender = new SelectList(db.adGenders, "GenderId", "GenderCode");
            ViewBag.GeographicTypeId = new SelectList(db.adGeographicTypes, "GeographicTypeId", "Code");
            ViewBag.LeadgrpId = new SelectList(db.adLeadGroups, "LeadGrpId", "Descrip");
            ViewBag.MaritalStatus = new SelectList(db.adMaritalStatus, "MaritalStatId", "MaritalStatCode");
            ViewBag.Nationality = new SelectList(db.adNationalities, "NationalityId", "NationalityCode");
            ViewBag.SourceAdvertisement = new SelectList(db.adSourceAdvertisements, "SourceAdvId", "SourceAdvDescrip");
            ViewBag.SourceCategoryID = new SelectList(db.adSourceCatagories, "SourceCatagoryId", "SourceCatagoryDescrip");
            ViewBag.SourceTypeID = new SelectList(db.adSourceTypes, "SourceTypeId", "SourceTypeDescrip");
            ViewBag.CampaignId = new SelectList(db.adVendorCampaigns, "CampaignId", "CampaignCode");
            ViewBag.AttendTypeId = new SelectList(db.arAttendTypes, "AttendTypeId", "Code");
            ViewBag.HousingId = new SelectList(db.arHousings, "HousingId", "Code");
            ViewBag.AreaID = new SelectList(db.arPrgGrps, "PrgGrpId", "PrgGrpCode");
            ViewBag.PrgVerId = new SelectList(db.arPrgVersions, "PrgVerId", "PrgVerCode");
            ViewBag.ProgramID = new SelectList(db.arPrograms, "ProgId", "ProgCode");
            ViewBag.ProgramScheduleId = new SelectList(db.arProgSchedules, "ScheduleId", "Code");
            ViewBag.ShiftID = new SelectList(db.arShifts, "ShiftId", "ShiftCode");
            ViewBag.AddressType = new SelectList(db.plAddressTypes, "AddressTypeId", "AddressDescrip");
            ViewBag.CampusId = new SelectList(db.syCampuses, "CampusId", "CampCode");
            ViewBag.FamilyIncome = new SelectList(db.syFamilyIncomes, "FamilyIncomeID", "FamilyIncomeDescrip");
            ViewBag.HighSchoolId = new SelectList(db.syInstitutions, "HSId", "HSCode");
            ViewBag.Prefix = new SelectList(db.syPrefixes, "PrefixId", "PrefixCode");
            ViewBag.DrivLicStateID = new SelectList(db.syStates, "StateId", "StateCode");
            ViewBag.EnrollStateId = new SelectList(db.syStates, "StateId", "StateCode");
            ViewBag.StateId = new SelectList(db.syStates, "StateId", "StateCode");
            ViewBag.LeadStatus = new SelectList(db.syStatusCodes, "StatusCodeId", "StatusCode");
            ViewBag.AddressStatus = new SelectList(db.syStatuses, "StatusId", "Status");
            ViewBag.PhoneStatus = new SelectList(db.syStatuses, "StatusId", "Status");
            ViewBag.StudentStatusId = new SelectList(db.syStatuses, "StatusId", "Status");
            ViewBag.Suffix = new SelectList(db.sySuffixes, "SuffixId", "SuffixCode");
            ViewBag.AdmissionsRep = new SelectList(db.syUsers, "UserId", "FullName");
            ViewBag.VendorId = new SelectList(db.syUsers, "UserId", "FullName");
            return View();
        }

        // POST: adLeads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LeadId,ProspectID,FirstName,LastName,MiddleName,SSN,ModUser,ModDate,Phone,HomeEmail,Address1,Address2,City,StateId,Zip,LeadStatus,WorkEmail,AddressType,Prefix,Suffix,BirthDate,Sponsor,AdmissionsRep,AssignedDate,Gender,Race,MaritalStatus,FamilyIncome,Children,PhoneType,PhoneStatus,SourceCategoryID,SourceTypeID,SourceDate,AreaID,ProgramID,ExpectedStart,ShiftID,Nationality,Citizen,DrivLicStateID,DrivLicNumber,AlienNumber,Comments,SourceAdvertisement,CampusId,PrgVerId,Country,County,Age,PreviousEducation,AddressStatus,CreatedDate,RecruitmentOffice,OtherState,ForeignPhone,ForeignZip,LeadgrpId,DependencyTypeId,DegCertSeekingId,GeographicTypeId,HousingId,admincriteriaid,DateApplied,InquiryTime,AdvertisementNote,Phone2,PhoneType2,PhoneStatus2,ForeignPhone2,DefaultPhone,IsDisabled,IsFirstTimeInSchool,IsFirstTimePostSecSchool,EntranceInterviewDate,ProgramScheduleId,BestTime,DistanceToSchool,CampaignId,ProgramOfInterest,CampusOfInterest,TransportationId,NickName,AttendTypeId,PreferredContactId,AddressApt,NoneEmail,HighSchoolId,HighSchoolGradDate,AttendingHs,StudentId,StudentNumber,StudentStatusId,ReasonNotEnrolledId,EnrollStateId,VendorId,AfaStudentId")] adLead adLead)
        {
            this.db = this.getAdvantageDb();
            if (this.db == null)
            {
                return Redirect(FormsAuthentication.LoginUrl);
            }

            if (ModelState.IsValid)
            {
                adLead.LeadId = Guid.NewGuid();
                db.adLeads.Add(adLead);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.admincriteriaid = new SelectList(db.adAdminCriterias, "admincriteriaid", "Code", adLead.admincriteriaid);
            ViewBag.Sponsor = new SelectList(db.adAgencySponsors, "AgencySpId", "AgencySpCode", adLead.Sponsor);
            ViewBag.Citizen = new SelectList(db.adCitizenships, "CitizenshipId", "CitizenshipCode", adLead.Citizen);
            ViewBag.County = new SelectList(db.adCounties, "CountyId", "CountyCode", adLead.County);
            ViewBag.Country = new SelectList(db.adCountries, "CountryId", "CountryCode", adLead.Country);
            ViewBag.DegCertSeekingId = new SelectList(db.adDegCertSeekings, "DegCertSeekingId", "Code", adLead.DegCertSeekingId);
            ViewBag.DependencyTypeId = new SelectList(db.adDependencyTypes, "DependencyTypeId", "Code", adLead.DependencyTypeId);
            ViewBag.PreviousEducation = new SelectList(db.adEdLvls, "EdLvlId", "EdLvlCode", adLead.PreviousEducation);
            ViewBag.Race = new SelectList(db.adEthCodes, "EthCodeId", "EthCode", adLead.Race);
            ViewBag.Gender = new SelectList(db.adGenders, "GenderId", "GenderCode", adLead.Gender);
            ViewBag.GeographicTypeId = new SelectList(db.adGeographicTypes, "GeographicTypeId", "Code", adLead.GeographicTypeId);
            ViewBag.LeadgrpId = new SelectList(db.adLeadGroups, "LeadGrpId", "Descrip", adLead.LeadgrpId);
            ViewBag.MaritalStatus = new SelectList(db.adMaritalStatus, "MaritalStatId", "MaritalStatCode", adLead.MaritalStatus);

Advantage/ExternalApplications/AdvantageDataFixer/AdvantageDataFixer/Views/Leads/Index.cshtml
@using GridMvc.Html
@model IEnumerable<AdvantageDataFixer.Models.adLead>

@{
    ViewBag.Title = "Students";
}


<h2>Students</h2>


<div class="form-horizontal">
    <div class="form-group">
        @Html.Label("Student Number Quick Search", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-6">
                    @Html.Editor("searchText", new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-md-2">
                    <button class="btn" id="quickSearchBtn">Search</button>
                </div>
                <div class="col-md-2">
                    <button class="btn" id="clearFiltersbtn">Clear Grid Filters</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="width:1000px;">
    @Html.Grid(Model).Columns(columns =>
{
    columns.Add(c => c.FirstName).Titled("First Name").Filterable(true);
    columns.Add(c => c.LastName).Titled("Last Name").Filterable(true);
    columns.Add(c => c.StudentNumber).Titled("ADV Student Number").Filterable(true);
    columns.Add().Titled("ADV Student Number").Encoded(false).Sanitized(false).RenderValueAs(data => Html.ActionLink("Edit", "Edit", "Leads", new { id = data.LeadId }, new { }).ToHtmlString());
    columns.Add(c => c.AfaStudentId).Titled("AFA Student Id").Filterable(true);
    columns.Add().Titled("AFA Student Id").Encoded(false).Sanitized(false).RenderValueAs(data => Html.ActionLink("Edit", "EditAfaStudentId", "Leads", new { id = data.LeadId }, new { }).ToHtmlString());
    columns.Add(c => c.LeadId).Titled("Options").Encoded(false).Sanitized(false).RenderValueAs(data => Html.ActionLink("Awards", "Index", "Awards", new { id = data.LeadId }, new { }).ToHtmlString() + " | " +  Html.ActionLink("Ledger", "Index", "Transactions", new { id = data.LeadId }, new { }).ToHtmlString());
}).WithPaging(20).Sortable(true)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            var searchedItem = window.location.href.split('?grid-filter=StudentNumber__2__');

            if (searchedItem.length > 1) {
                $('#searchText').val(window.location.href.split('?grid-filter=StudentNumber__2__')[1]);
            }
        });

        $('#quickSearchBtn').on('click', function () {
            window.location.href = window.location.href.split('?')[0] + "?grid-filter=StudentNumber__2__" + $('#searchText').val();
        })

        $('#clearFiltersbtn').on('click', function () {
            window.location.href = window.location.href.split('?')[0];
        })
    </script>
}