Advantage/ExternalApplications/AdvantageDataFixer/AdvantageDataFixer/Controllers/TransactionsController.cs
using AdvantageDataFixer.Models;
using AdvantageDataFixer.Models.PrebuiltQueries;
using AdvantageDataFixer.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AdvantageDataFixer.Controllers
{
    using System.Globalization;
    using System.Web.Security;

    [Authorize]
    public class TransactionsController : AuthorizedController
    {
        private AdvantageDb db;

        // GET: Transactions/Index/guid
        public ActionResult Index(string id)
        {
            this.db = this.getAdvantageDb();
            if (this.db == null)
            {
                return Redirect(FormsAuthentication.LoginUrl);
            }

            var saTransactions = db.saTransactions
                .Include(s => s.arPrgChargePeriodSeq)
                .Include(s => s.arStuEnrollment)
                .Include(s => s.arTerm)
                .Include(s => s.saAcademicYear.AcademicYearDescrip)
                .Include(s => s.saBatchPayment)
                .Include(s => s.saFundSource)
                .Include(s => s.saPayment)
                .Include(s => s.saPmtPeriod)
                .Include(s => s.saRefund)
                .Include(s => s.saTransCode)
                .Include(s => s.saTransCode1)
                .Include(s => s.saTransType)
                .OrderBy(a => a.TransDate).ThenBy(a => a.ModDate).AsNoTracking();

            //if id is pased filter transactions by student number
            if (id != null)
            {
                id = id.Trim();
                var studentsEnrollments = db.GetEnrollmentsIdsByStudentNumber(id);
                saTransactions = saTransactions.Where(a => studentsEnrollments.Any(b => b.StuEnrollId == a.StuEnrollId) && a.Voided == false);

                var adLead = db.adLeads.Where(a => a.LeadId.ToString() == id).FirstOrDefault();
                ViewBag.Title = $"Ledger - {adLead.StudentNumber} - {adLead.FirstName} {adLead.LastName}";
            }
            else
            {
                ViewBag.Title = "All Ledger Transactions";
            }

            var data = saTransactions.Select(a => new TransactionVM()
            {
                StuEnrollId = a.StuEnrollId.ToString(),
                Date = a.TransDate,
                Reference = a.TransReference,
                DocumentId = a.saPayment.CheckNumber,
                TransCode = a.saTransCode1 != null ? a.saTransCode1.TransCodeDescrip : null,
                Description = a.TransDescrip,
                AcademicYear = a.saAcademicYear.AcademicYearDescrip,
                Term = a.arTerm != null ? a.arTerm.TermDescrip : null,
                TransType = a.saTransType != null ? a.saTransType.Description : null,
                User = a.ModUser,
                Amount = a.TransAmount.ToString(),
                Balance = string.Empty,
                PaymentPeriod = a.PaymentPeriodNumber.ToString(),
                PaymentTypeId = a.saPayment != null ? (int?)a.saPayment.PaymentTypeId : null,
                TransactionId = a.TransactionId.ToString(),
                HasPaymentTiedToTransaction = a.saPayment != null
            }).ToList();

            foreach (var item in data)
            {
                switch (item.PaymentTypeId)
                {
                    case 2:
                        item.DocumentId = "Check Number: " + item.DocumentId;
                        break;
                    case 3:
                        item.DocumentId = "C/C Authorization: " + item.DocumentId;
                        break;
                    case 4:
                        item.DocumentId = "EFT Number: " + item.DocumentId;
                        break;
                    case 5:
                        item.DocumentId = "Money Order Number: " + item.DocumentId;
                        break;
                    case 6:
                        item.DocumentId = "Non Cash Reference #: " + item.DocumentId;
                        break;
                }
            }

            ViewBag.StudentNumber = id;
            return View(data);
        }

        // GET: Transactions/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            this.db = this.getAdvantageDb();
            if (this.db == null)
            {
                return Redirect(FormsAuthentication.LoginUrl);
            }

            saTransaction saTransaction = db.saTransactions.Find(id);
            if (saTransaction == null)
            {
                return HttpNotFound();
            }
            return View(saTransaction);
        }

        public ActionResult AwardLinking(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            this.db = this.getAdvantageDb();
            if (this.db == null)
            {
                return Redirect(FormsAuthentication.LoginUrl);
            }

            TransactionAwardLinkVM saTransaction = db.saTransactions
                .Include(a => a.arStuEnrollment.adLead)
                .Where(a => a.TransactionId == id)
                .Select(t => new TransactionAwardLinkVM
                {
                    EnrollmentId = t.StuEnrollId,
                    TransactionId = t.TransactionId,
                    TransactionType = t.TransDescrip.ToLower().Contains("Refund") ? "Refund" : t.TransDescrip.ToLower().Contains("Disb") ? "Disbursement" : string.Empty
                }).FirstOrDefault();

            saTransaction saTransaction1 = db.saTransactions.Include(a => a.arStuEnrollment.adLead).Include(a => a.saTransCode1).Where(a => a.TransactionId == id).FirstOrDefault();
            ViewBag.Title = saTransaction1.TransDescrip + " - " + saTransaction1.saTransCode1.TransCodeDescrip + " - " + saTransaction1.TransAmount + " -----  Student: " +
                            saTransaction1.arStuEnrollment.adLead.StudentNumber + " - " +
                            saTransaction1.arStuEnrollment.adLead.FirstName + " " +
                            saTransaction1.arStuEnrollment.adLead.LastName + "";

            if (saTransaction == null)
                return HttpNotFound();


            System.Guid currentScheduleId = Guid.Empty;
            faStudentAwardSchedule currentSchedule = db.faStudentAwardSchedules
                .Where(s => s.TransactionId == saTransaction.TransactionId).FirstOrDefault();

            if (currentSchedule != null)
                currentScheduleId = currentSchedule.AwardScheduleId;


            if (saTransaction.TransactionType == "Refund")
            {
                var refund = this.db.saRefunds.Where(
                        r => r.TransactionId == saTransaction.TransactionId )
                    .FirstOrDefault();

                if (refund != null && refund.AwardScheduleId.HasValue)
                {
                    currentScheduleId = refund.AwardScheduleId.Value;
                }
            }


            if (saTransaction.TransactionType == "Disbursement")
            {
                var disb = this.db.saPmtDisbRels.Where(
                        r => r.TransactionId == saTransaction.TransactionId)
                    .FirstOrDefault();

                if (disb != null && disb.AwardScheduleId.HasValue)
                {
                    currentScheduleId = disb.AwardScheduleId.Value;
                }
            }

            var transactionTypes = new Dictionary<string, string>()
                                       {
                                           {string.Empty, "Select"},{"Disbursement", "Disbursement"}, { "Refund", "Refund"}
                                       };

            var schedules = this.db.faStudentAwardSchedules
                .Include(s=> s.faStudentAward.saFundSource)
                .Where(s => s.faStudentAward.StuEnrollId == saTransaction.EnrollmentId )
                .AsEnumerable()
                .Select(s => new KeyValuePair<Guid, string>
                    (s.AwardScheduleId, (s.faStudentAward.saFundSource.FundSourceDescrip) + " (" + s.faStudentAward.AwardStartDate.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture) + ") - " + (s.ExpectedDate?.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture) ?? ""))).OrderBy(t => t.Value).ToList();


            ViewBag.TransactionType = new SelectList(transactionTypes, "Key", "Value", saTransaction.TransactionType);

            ViewBag.StudentAwardScheduleId = new SelectList(schedules, "Key", "Value", currentScheduleId);
            return View(saTransaction);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AwardLinking(TransactionAwardLinkVM link)
        {
            this.db = this.getAdvantageDb();
            if (this.db == null)
            {
                return Redirect(FormsAuthentication.LoginUrl);
            }

            faStudentAwardSchedule award = this.db.faStudentAwardSchedules
                .Where(a => a.AwardScheduleId == link.StudentAwardScheduleId).FirstOrDefault();

            saTransaction transaction = this.db.saTransactions.Include(a => a.arStuEnrollment.adLead).Where(t => t.TransactionId == link.TransactionId)
                .FirstOrDefault();

            if (link.TransactionType == "Refund")
            {

                var refund = this.db.saRefunds.Where(
                        r => r.TransactionId == link.TransactionId || r.AwardScheduleId == link.StudentAwardScheduleId)
                    .FirstOrDefault();

                if (refund != null)
                {
                    refund.AwardScheduleId = link.StudentAwardScheduleId;
                    refund.TransactionId = link.TransactionId;

                    //if fund source id has value

Advantage/ExternalApplications/AdvantageDataFixer/AdvantageDataFixer/Views/Transactions/AwardLinking.cshtml
<style>
    select{
        max-width: 600px !important;
    }

</style>
@model AdvantageDataFixer.ViewModels.TransactionAwardLinkVM

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.HiddenFor(model => model.TransactionId)
    <div class="form-group">
        @Html.LabelFor(model => model.TransactionType, "TransactionType", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TransactionType", null, "Select", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TransactionType, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.StudentAwardScheduleId, "StudentAwardScheduleId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StudentAwardScheduleId", null, "Select", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StudentAwardScheduleId, "", new { @class = "text-danger" })
        </div>
    </div>
    
    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}


<div>
    @Html.ActionLink("Back to List", null, null, null, new { href = Request.UrlReferrer })
    @*@Html.ActionLink("Back to List", "Index", new { id = ViewBag.StudentNumber })*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Advantage/ExternalApplications/AdvantageDataFixer/AdvantageDataFixer/Views/Transactions/Create.cshtml
@model AdvantageDataFixer.Models.saTransaction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>saTransaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StuEnrollId, "StuEnrollId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StuEnrollId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StuEnrollId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TermId, "TermId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TermId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TermId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CampusId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CampusId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CampusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransCodeId, "TransCodeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TransCodeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TransCodeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransReference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransReference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransReference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AcademicYearId, "AcademicYearId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AcademicYearId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AcademicYearId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransDescrip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransDescrip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransDescrip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransTypeId, "TransTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TransTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TransTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPosted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPosted)
                    @Html.ValidationMessageFor(model => model.IsPosted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BatchPaymentId, "BatchPaymentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BatchPaymentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BatchPaymentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ViewOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ViewOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAutomatic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAutomatic)
                    @Html.ValidationMessageFor(model => model.IsAutomatic, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Voided, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Voided)
                    @Html.ValidationMessageFor(model => model.Voided, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FeeLevelId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FeeLevelId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FeeLevelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentCodeId, "PaymentCodeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PaymentCodeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PaymentCodeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FundSourceId, "FundSourceId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FundSourceId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FundSourceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StuEnrollPayPeriodId, "StuEnrollPayPeriodId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StuEnrollPayPeriodId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StuEnrollPayPeriodId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisplaySequence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DisplaySequence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisplaySequence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondDisplaySequence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondDisplaySequence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondDisplaySequence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PmtPeriodId, "PmtPeriodId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PmtPeriodId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PmtPeriodId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrgChrPeriodSeqId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrgChrPeriodSeqId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrgChrPeriodSeqId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentPeriodNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentPeriodNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentPeriodNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Advantage/ExternalApplications/AdvantageDataFixer/AdvantageDataFixer/Views/Transactions/Index.cshtml
@model IEnumerable<AdvantageDataFixer.ViewModels.TransactionVM>
@using GridMvc.Html

<h2>@ViewBag.Title</h2>

@*<div class="row">
    <div class="col-md-10"></div>
    <div class="col-md-1">
        <input type="button" style="width:100%;" class="btn-primary" value="Create" onclick="location.href='@Url.Action("Create", "Transactions", new { StudentId = (string)ViewBag.StudentId })'" />
    </div>
    <div class="col-md-1">
        <input type="button" style="width:100%;" class="btn-primary" value="Edit Selected" onclick="location.href='@Url.Action("Create", "User")'" />
    </div>
</div>*@

<div style="width:100%;">
    @Html.Grid(Model).Columns(columns =>
{
    columns.Add(c => c.TransactionId).Titled("Select").Encoded(false).Sanitized(false).RenderValueAs(data => "<input type=\"Checkbox\" data-id=\"" +data.TransactionId+"\" />");
    columns.Add(c => c.Date).Format("{0:MM/dd/yyyy}").Titled("Date").Filterable(true);
    columns.Add(c => c.Reference).Titled("Reference").Filterable(true);
    columns.Add(c => c.DocumentId).Titled("Document ID").Filterable(true);
    columns.Add(c => c.TransCode).Titled("Trans. Code").Filterable(false);
    columns.Add(c => c.Description).Titled("Description").Filterable(true);
    columns.Add(c => c.AcademicYear).Titled("Academic Year").Filterable(true);
    columns.Add(c => c.Term).Titled("Term").Filterable(true);
    columns.Add(c => c.TransType).Titled("Trans. Type").Filterable(true);
    columns.Add(c => c.User).Titled("User").Filterable(true);
    columns.Add(c => c.Amount).Format("{0:c}").Titled("Amount").Filterable(true);
    //columns.Add(c => c.Balance).Format("{0:c}").Titled("Balance").Filterable(true);
    columns.Add(c => c.PaymentPeriod).Titled("Payment Period").Filterable(true);
    //columns.Add(c => c.HasPaymentTiedToTransaction).Titled("Has Tied FK").Filterable(true);
    columns.Add(c => c.PaymentTypeId).Titled("Options").Encoded(false).Sanitized(false).RenderValueAs(data => Html.ActionLink("Edit", "Edit", "Transactions", new { id = data.TransactionId }, new { }).ToHtmlString() + " | " + Html.ActionLink("Delete", "Delete", "Transactions", new { id = data.TransactionId }, new { }).ToHtmlString() + " | " + Html.ActionLink("Link", "AwardLinking", "Transactions", new { id = data.TransactionId }, new { }).ToHtmlString());
    //columns.Add(c => c.arTerm).Titled("Options").Encoded(false).Sanitized(false).RenderValueAs(data => Html.ActionLink("Awards", "Index", "Awards").ToHtmlString() + " | " +  Html.ActionLink("Ledger", "Index", "Transactions", new { id = data.arTerm }, new { }).ToHtmlString());
}).WithPaging(25).Sortable(true)
</div>

<h4>Number of records: @Model.Count()</h4>